Kevin2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('category/', views.CategoryListView.as_view(), name='categorias'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('update/<pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('category/<str:cats>/', views.CategoryView, name='category'),

]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from email.policy import default
from django.db import models
from django.conf import settings
from django.utils.timezone import now


class Category(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return f'"{self.nome}" - {self.descricao}'

class Post(models.Model):
    titulo = models.CharField(max_length=255)
    conteudo = models.TextField()
    data = models.DateTimeField(default=now, blank=True)
    category = models.ManyToManyField(Category)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL,
                            #    on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.titulo} ({self.data})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data = models.DateTimeField(default=now, blank=True)
    likes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-data']

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Comment, Category


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'titulo',
            'conteudo',
            'data',
        ]
        labels = {
            'titulo': 'Título',
            'conteudo': 'Conteúdo',
            'data': 'Data',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'data',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
            'data': 'Data',
        }

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.views import generic


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'
    allow_empty = False


# def detail_post(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     context = {'post': post}
#     return render(request, 'posts/detail.html', context)


class PostListView(generic.ListView):
    model = Post
    form_class = PostForm
    template_name = 'posts/index.html'
    sucess_url = '/posts/'
    
# def list_posts(request):
#     post_list = Post.objects.all()
#     context = {"post_list": post_list}
#     return render(request, 'posts/index.html', context)


class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create.html'
    success_url = '/posts/'


# def create_post(request):

#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():

#             post_titulo = request.POST['titulo']
#             post_conteudo = request.POST['conteudo']
#             post_data = request.POST['data']

#             post = Post(titulo = post_titulo,
#                         conteudo = post_conteudo,
#                         data = post_data)
#             post.save()

#             return HttpResponseRedirect(reverse('posts:detail', args=(post.id, )))
#     else:
#         form = PostForm()
#     context = {'form' : form}
#     return render(request, 'posts/create.html', context)

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update.html'
    success_url = '/posts/'

# def update_post(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if request.method == "POST":

#         form = PostForm(request.POST)

#         if form.is_valid():

#             post.titulo = request.POST['titulo']
#             post.conteudo = request.POST['conteudo']
#             post.data = request.POST['data']
#             post.save()

#             return HttpResponseRedirect(reverse('posts:detail', args=(post.id, )))
    
#     else:
#         form = PostForm(
#             initial = {
#             'titulo': post.titulo,
#             'conteudo': post.conteudo,
#             'data': post.data              
#             })

#     context = {'post' : post, 'form' : form}
#     return render(request, 'posts/update.html', context)


class PostDeleteView(generic.DeleteView):
    model = Post
    success_url = '/posts/'
    template_name = 'posts/delete.html'
    allow_empty = False

# def delete_post(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if request.method == "POST":
#         post.delete()
#         return HttpResponseRedirect(reverse('posts:index'))

#     context = {'post': post}
#     return render(request, 'posts/delete.html', context)

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categorias.html'

def CategoryView(request, cats):
    category = get_object_or_404(Category, nome = cats)
    return render(request, 'posts/categories.html', { 'category' : category })

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/categorias.html
{% extends 'base.html' %}

{% block content %}

<h2>Todas as categorias</h2>

{% if category_list %}
<section class="lista-de-cards">
    {% for categoria in category_list %}
    <article class="card">
        <a href="{% url 'posts:category' categoria.nome %}"> {{ categoria.nome }} </a>
        <p> - {{ categoria.descricao }} </p>
    </article>
    {% endfor %}
</section>

{% else %}

<h2> Ainda não há nenhuma categoria :( ... </h2>

{% endif %}

{% endblock content %}

posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}


<h2> {{ category.nome }} </h2>

<p> - {{category.descricao}}</p>


{% for post in category.post_set.all %}

<article class="card">
    <a href="{% url 'posts:detail' post.id %}"> {{ post.titulo }} </a>
    <p>{{ post.data | date }}</p>
</article>
{% endfor %}




{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar no post {{ post.titulo }} postado em {{ post.data | date }}</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a postagem "{{ post.titulo }} publicada em: ({{ post.data | date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.titulo }} ({{ post.data | date }}
{% endblock title %}

{% block content %}

<section class="dados-de-post">
    <h1> {{ post.titulo }} </h1>

    {{ post.conteudo | safe }}


    <p style="font-size : 10px; "> Postado em: {{ post.data | date }}</p>


    {% if post.category.all %}

    <p> Categorias: </p>

    {% for categoria in post.category.all %}

    <li><a href="{% url 'posts:category' categoria.nome %}"> {{ categoria.nome }}</a> </li>
    {% endfor %}
    {%endif%}

    <hr>

    <ul>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>


</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>— {{ comment.author }} em {{ comment.data | date }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário nesta postagem.</p>
        {% endif %}
    </ul>


    <a href="{% url 'posts:comment' post.id %}"><button>Deixe seu comentário</button></a>

</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todas as postagens</h2>
<section>
    <p> Crie seu post! <a href="{% url 'posts:create' %}">Adicionar Novo post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"> {{ post.titulo }} </a>
        <p> - {{ post.data | date }} </p>
        
    </article>

    {% endfor %}

</section>

{% else %}

<p>Não foi encontrado nenhuma postagem.</p>

{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Postagem {{ post.titulo }} ({{ post.data | date}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<p>Este é simplesmente o site mais importante da internet moderna. Caso tenha alguma dúvida sobre qualquer tópico, se estiver escrito aqui é a verdade. </p>

<p> Escrito por Kevin "em Pessoa" </p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Blog do Kevin</i></h1>
<p>A Página para discutir os assuntos mais importantes do momento com Kevin, o cão</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Blog do Kevin
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>KEVIN</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:categorias' %}">Categorias</a></li>
                <li><a href="{% url 'posts:index' %}">Postagens</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>